export { default as Home } from './Main'
export { default as Post } from './Post'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as NotFound } from './NotFound'